### ISSUE TITLE
MQTT server is not saved persistently

### ISSUE THREAD

**Issue by cederlys** [AnaviTechnology/anavi-thermometer-sw#1] opened 2019-04-03 11:31 UTC
I got my thermometers the other day. Setup was easy. I used my own MQTT server,
and things just worked as long as the thermometer was powered up.  But after removing
power and re-applying it, I received no updates at the MQTT server.  Sniffing the network
I discovered that the updates were sent to iot.eclipse.org instead of my server.

The thermometer does remember which WiFi network to connect to, and the WiFi
password, but apparently not the MQTT server name.

As a workaround I've edited the source code and changed mqtt_server to the server
I want to use, and re-flashed the thermometer.  Now it seems to work.  But I was under
the impression that I shouldn't need to do that.

**Comment by leon-anavi** [comment] 2019-04-03 19:10
Hi @cederlys,

Sorry for the inconvenience. This must have been caused by wrong configurations of the flash size in Arduino IDE when the default firmware has been flashed. [I have updated the instructions in the user's manual](https://github.com/AnaviTechnology/anavi-docs/blob/master/anavi-thermometer/anavi-thermometer.md#setting-up-the-arduino-ide). 

Could you please select **4M (1M SPIFFS)** for **Flash Size** in menu **Tools** and after that flash again the default firmware?

With this update of the configuration in Arduino IDE the default firmware will be able to access the SPI flash and store the configured mqtt broker. Sorry again for the inconvenience.

Thanks,
Leon

**Comment by cederlys** [comment] 2019-04-03 21:57
Yes, that seems to have fixed the issue. Thanks.

**Comment by leon-anavi** [comment] 2019-04-03 22:01
Thank you for the feedback and the confirmation. I will close the issue.

Thanks,
Leon

**Closed as completed by leon-anavi** 2019-04-03 22:01 UTC
